### ISSUE TITLE
The demo seems to be wrong.

### ISSUE THREAD

**Issue by Waynefong** [shikijs/shiki-magic-move#21] opened 2024-07-18 04:58 UTC
Hi Tony,

I have updated the [shiki] version to the latest. I want to use [shiki-magic-move] to animate the code. However, 'getHighlighter' was deprecated, so I changed it to 'createHighlighter'. The rest of the code is the same as in the demo.

After making the changes, the [ShikiMagicMove] component still doesn't work. Additionally, it seems like my VSCode's system usage is continuously increasing. Could you modify the demo for me so I can learn from it?

**Comment by antfu** [comment] 2024-07-23 17:01
We temporarily closed this due to the lack of enough information. We could not identify whether it was a bug or a userland misconfiguration with the given info.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed by antfu** 2024-07-23 17:01 UTC
